### ISSUE TITLE
What is MD?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [fraser125/N64-ASM-Tutorial#2]
In lesson 1,

> Common commands: CD, MD, DIR.

In cmd prompt I get "The syntax of the command is incorrect." for md.

**Comment by fraser125** [comment]
It's a bad error message but this screen capture probably shows what you need to know. 
![image](https://user-images.githubusercontent.com/1725115/140694698-2bd40a22-4355-4e29-8264-5dbc35de82bf.png)
